{{- if .Values.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ (default (include "cronjob.defaultContainerName" .) (include "cronjob.fullname" .)) }}
  namespace: {{ .Values.namespace }}
immutable: {{ .Values.configMap.immutable }}
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}