apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}
  labels:
    {{- include "<CHARTNAME>.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "<CHARTNAME>.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        app.wepayments.com.br/version: {{ required "A valid .Values.image.tag entry is required!" .Values.image.tag | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "<CHARTNAME>.selectorLabels" . | nindent 8 }}
    spec:
      # Image pull secrets, used to download images from the registry (e.g. DockerHub)
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # Pod service account name
      serviceAccountName: {{ include "<CHARTNAME>.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      # Pod security context
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.deployment.containerPorts }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.probes.liveness }}
          # Liveness
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.probes.readiness }}
          # Readiness
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.deployment.probes.startup }}
          # Startup
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          # Container resource usage
          resources:
            {{- toYaml (required "A valid .Values.resources entry is required!" (ternary nil .Values.resources (eq (toJson .Values.resources) "{}"))) | nindent 12 }}
          {{- with .Values.extraEnv }}
          # Extra env
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraEnvFrom }}
          # Extra envFrom
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.overrideCommand }}
          # Overriding command
          command:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.extraArgs }}
          # Extra arguments
          args:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      # Pod node selectors
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      # Pod affinities
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      # Pod tolerations
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
