{{- if .Values.destinationRules.enabled }}
{{- range .Values.destinationRules.rules }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ (include "deployment.fullname" $) }}{{ (ternary (print "-" .nameSuffix) "" (not (empty .nameSuffix))) }}
  labels:
    {{- include "deployment.labels" $ | nindent 4 }}
  annotations:
    app.wepayments.com.br/version: {{ .Values.image.tag | quote }}
spec:
  host: {{ (ternary .host (include "deployment.serviceName" $) (not (empty .host))) | quote }}
  {{- with .trafficPolicy }}
  trafficPolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .subsets }}
  subsets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .exportsTo }}
  exportsTo:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
{{- end }}
