{{- if .Values.virtualServices.enabled }}
{{- range $vs := .Values.virtualServices.services }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ (include "deployment.fullname" $) }}{{ (ternary (print "-" $vs.nameSuffix) "" (not (empty $vs.nameSuffix))) }}
  labels:
    {{- include "deployment.labels" $ | nindent 4 }}
  annotations:
    app.wepayments.com.br/version: {{ .Values.image.tag | quote }}
spec:
  {{- with $vs.hosts }}
  hosts:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with $vs.gateways }}
  gateways:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  http:
    {{- if empty $vs.http }}
    - route:
        - destination:
            port:
              number: {{ $.Values.service.primaryPort.number }}
            host: {{ include "deployment.serviceName" $ }}
    {{- else }}
    {{- toYaml $vs.http | nindent 4 }}
    {{- end }}
---
{{- end }}
{{- end }}
