{{- if .Values.nodeTemplate.create }}
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: {{ .Values.nodeTemplate.name }}
  labels:
    {{- include "provisioner.labels" . | nindent 4 }}
{{- with .Values.nodeTemplate.spec }}
spec:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
