apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: {{ include "provisioner.fullname" . }}
  labels:
    {{- include "provisioner.labels" . | nindent 4 }}
spec:
  providerRef:
    name: {{ .Values.nodeTemplate.name }}

  {{- with .Values.taints }}
  taints:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.requirements }}
  requirements:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.kubeletConfiguration }}
  kubeletConfiguration:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.limits }}
  limits:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- with .Values.consolidation }}
  consolidation:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  ttlSecondsUntilExpired: {{ .Values.ttlSecondsUntilExpired }}
  ttlSecondsAfterEmpty: {{ .Values.ttlSecondsAfterEmpty }}
